apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: accelerators-list 
  namespace: accelerator-system
spec:
  serviceAccountName: accelerator-controller-manager

  fetch:
  - git:
      url: https://github.com/tfynes-pivotal/accelerators-list
      ref: origin/main

      subPath: accelerators

  template:
  - ytt: {}
  deploy: 
  - kapp: {}
